"""Aurival bot SDK.

Declare commands, call run(), and the SDK holds the socket::

    from aurival import Bot

    bot = Bot()

    @bot.command("ping")
    async def ping(ctx):
        await ctx.reply("pong")

    bot.run()
"""

from __future__ import annotations

from .bot import Bot
from .cooldown import Cooldown
from .embeds import Button, ButtonUsed, Embed
from .errors import (
    CODE_CLASSES,
    DOC_URL_PREFIX,
    TYPE_CLASSES,
    AccessTokenExpired,
    AccessTokenInvalid,
    AckUnknownEvent,
    APIError,
    AssertionExpired,
    AssertionReplay,
    AurivalAPIError,
    AurivalError,
    AuthenticationError,
    AuthorURLWithoutName,
    BadAssertion,
    BadProof,
    BadPublicKey,
    BotLinkNotAllowed,
    BotPlaygroundOnly,
    BotSuspended,
    ButtonAlreadyUsed,
    ButtonIDTooLong,
    ButtonLabelTooLong,
    ButtonMissingField,
    ButtonsWithoutMessage,
    CooldownRetryAfterInvalid,
    CooldownWithBody,
    DuplicateButtonID,
    EmbedAuthorNameTooLong,
    EmbedDescriptionTooLong,
    EmbedEmpty,
    EmbedFieldNameTooLong,
    EmbedFieldValueTooLong,
    EmbedFooterTextRequired,
    EmbedFooterTextTooLong,
    EmbedsTooLong,
    EmbedTitleTooLong,
    EmbedURLNotHTTPS,
    EmbedURLWithoutTitle,
    EmptyText,
    ForUserNotMember,
    FrameInvalid,
    FrameTooLarge,
    IdempotencyKeyInvalid,
    IdempotencyKeyReused,
    IdleTimeout,
    ImageURLTooLong,
    InternalError,
    InvalidButtonEmoji,
    InvalidButtonStyle,
    InvalidCommandName,
    InvalidJSON,
    InvalidRequestError,
    KeyAlreadyPaired,
    KeyRevoked,
    LinkButtonMissingURL,
    LinkButtonNotSupported,
    LinkURLNotHTTPS,
    LinkURLTooLong,
    MentionNotMember,
    MentionTokenMissing,
    MessageNotYours,
    NotFound,
    NothingToEdit,
    PairRateLimited,
    ParameterInvalid,
    ParameterMissing,
    PermissionDeniedError,
    ProtocolError,
    RateLimited,
    RateLimitError,
    ReactionEmojiTooLong,
    ServerRestarting,
    SessionSuperseded,
    SyncRateLimited,
    TextTooLong,
    TooManyAliases,
    TooManyButtons,
    TooManyEmbedFields,
    TooManyEmbeds,
    TooManyProblems,
    TransportError,
    UnknownOperation,
    UnknownParameter,
    URLOnNonLinkButton,
    from_envelope,
)
from .events import (
    AnyContext,
    BaseContext,
    BotContext,
    ButtonContext,
    ButtonEventType,
    Chat,
    Command,
    Context,
    Event,
    EventContext,
    EventType,
    MemberContext,
    MemberPage,
    Mention,
    Message,
    ReactionContext,
    User,
    mention,
)
from .socket import BYE_ACTIONS, ByeAction, action_for_bye

__version__ = "0.8.0"

# Everything a developer can name. The JS package mirrors this list file for file
# (SDK-7), so a name missing here becomes a permanent asymmetry: adding an export
# later is free, removing one is a break.
__all__ = [
    "BYE_ACTIONS",
    "CODE_CLASSES",
    "DOC_URL_PREFIX",
    "TYPE_CLASSES",
    "APIError",
    "AccessTokenExpired",
    "AccessTokenInvalid",
    "AckUnknownEvent",
    "AnyContext",
    "AssertionExpired",
    "AssertionReplay",
    "AurivalAPIError",
    "AurivalError",
    "AuthenticationError",
    "AuthorURLWithoutName",
    "BadAssertion",
    "BadProof",
    "BadPublicKey",
    "BaseContext",
    "Bot",
    "BotContext",
    "BotLinkNotAllowed",
    "BotPlaygroundOnly",
    "BotSuspended",
    "Button",
    "ButtonAlreadyUsed",
    "ButtonContext",
    "ButtonEventType",
    "ButtonIDTooLong",
    "ButtonLabelTooLong",
    "ButtonMissingField",
    "ButtonUsed",
    "ButtonsWithoutMessage",
    "ByeAction",
    "Chat",
    "Command",
    "Context",
    "Cooldown",
    "CooldownRetryAfterInvalid",
    "CooldownWithBody",
    "DuplicateButtonID",
    "Embed",
    "EmbedAuthorNameTooLong",
    "EmbedDescriptionTooLong",
    "EmbedEmpty",
    "EmbedFieldNameTooLong",
    "EmbedFieldValueTooLong",
    "EmbedFooterTextRequired",
    "EmbedFooterTextTooLong",
    "EmbedsTooLong",
    "EmbedTitleTooLong",
    "EmbedURLNotHTTPS",
    "EmbedURLWithoutTitle",
    "EmptyText",
    "Event",
    "EventContext",
    "EventType",
    "ForUserNotMember",
    "FrameInvalid",
    "FrameTooLarge",
    "IdempotencyKeyInvalid",
    "IdempotencyKeyReused",
    "IdleTimeout",
    "ImageURLTooLong",
    "InternalError",
    "InvalidButtonEmoji",
    "InvalidButtonStyle",
    "InvalidCommandName",
    "InvalidJSON",
    "InvalidRequestError",
    "KeyAlreadyPaired",
    "KeyRevoked",
    "LinkButtonMissingURL",
    "LinkButtonNotSupported",
    "LinkURLNotHTTPS",
    "LinkURLTooLong",
    "MemberContext",
    "MemberPage",
    "Mention",
    "MentionNotMember",
    "MentionTokenMissing",
    "Message",
    "MessageNotYours",
    "NotFound",
    "NothingToEdit",
    "PairRateLimited",
    "ParameterInvalid",
    "ParameterMissing",
    "PermissionDeniedError",
    "ProtocolError",
    "RateLimitError",
    "RateLimited",
    "ReactionContext",
    "ReactionEmojiTooLong",
    "ServerRestarting",
    "SessionSuperseded",
    "SyncRateLimited",
    "TextTooLong",
    "TooManyAliases",
    "TooManyButtons",
    "TooManyEmbedFields",
    "TooManyEmbeds",
    "TooManyProblems",
    "TransportError",
    "URLOnNonLinkButton",
    "UnknownOperation",
    "UnknownParameter",
    "User",
    "__version__",
    "action_for_bye",
    "from_envelope",
    "mention",
]
